# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development: &development
  secret_key_base: fd88caa13f44a0f2bf99239d9da9d60905a3bf4552c99073d0642e3c7fd078ebf0ec4327e085f75823bc9ff39ea2d9f8f3cb9048712c8a8e59819931cba0f675
  expiration_date_days: <%= ENV['EXPIRATION_DATE_DAYS'] %>
  hmac_secret: 'secret'

test:
  <<: *development


# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  expiration_date_days: <%= ENV['EXPIRATION_DATE_DAYS'] %>
  hmac_secret: <%= ENV['HMAC_SECRET'] %>
